export const REGIONES = [
  "Arica y Parinacota",
  "Tarapacá",
  "Antofagasta",
  "Atacama",
  "Coquimbo",
  "Valparaíso",
  "Metropolitana de Santiago",
  "O'Higgins",
  "Maule",
  "Ñuble",
  "Biobío",
  "La Araucanía",
  "Los Ríos",
  "Los Lagos",
  "Aysén del General Carlos Ibáñez del Campo",
  "Magallanes y la Antártica Chilena",
];

export const RUBROS = [
  "Acuicultura / Salmonicultura",
  "Aduanas / Portuario",
  "Agricultura",
  "Banquetería/Eventos",
  "Comercio",
  "Construcción",
  "Corporación",
  "Deporte",
  "Energía",
  "Financiero",
  "Forestal / Silvicultura",
  "Fundación",
  "Ganadería",
  "Gastronomía",
  "Hotelería / Turismo",
  "Industria",
  "Lechería",
  "Minería",
  "Reciclaje",
  "Seguridad",
  "Servicios",
  "Tecnología/Informática",
  "Transporte",
];

export const CARGOS = [
  "Presidente",
  "Vicepresidente",
  "Miembro",
];
